# Generated by Django 3.1.7 on 2021-02-25 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('short_name', models.CharField(db_column='shortName', max_length=255)),
                ('distance_number', models.IntegerField(db_column='distanceNumber')),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='webapp.building')),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_hours', models.IntegerField(blank=True, db_column='teorikDersSaati', null=True)),
                ('practice_hours', models.IntegerField(blank=True, db_column='uygulamaDersSaati', null=True)),
                ('max_students', models.IntegerField(blank=True, db_column='maxOgrenciSayisi', null=True)),
                ('code', models.CharField(blank=True, db_column='dersKodu', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='dersAdi', max_length=255, null=True)),
                ('credits', models.IntegerField(blank=True, db_column='kredi', null=True)),
                ('etkin', models.IntegerField(blank=True, db_column='etkin', null=True)),
                ('sube', models.IntegerField(blank=True, db_column='sube', null=True)),
                ('unpositioned_theory_hours', models.IntegerField(blank=True, db_column='unpositionedTeorikHours', null=True)),
                ('unpositioned_practice_hours', models.IntegerField(blank=True, db_column='unpositionedUygulamaHours', null=True)),
                ('semester', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('type_code', models.IntegerField(db_column='typeCode', null=True)),
            ],
            options={
                'db_table': 'course_type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='webapp.building')),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='GradeYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_years', to='webapp.department')),
            ],
            options={
                'db_table': 'grade_year',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('type_code', models.IntegerField(db_column='typeCode', null=True)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, db_column='sicil', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('unvan', models.CharField(blank=True, db_column='unvan', max_length=255, null=True)),
                ('extra_data', models.CharField(blank=True, db_column='extraData', max_length=255, null=True)),
                ('employee_type', models.IntegerField(blank=True, db_column='employeeType', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TimeDay',
            fields=[
                ('id', models.PositiveIntegerField(db_column='idtimeDay', primary_key=True, serialize=False)),
                ('order_position', models.IntegerField(blank=True, db_column='orderPosition', null=True)),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'timeDay',
            },
        ),
        migrations.CreateModel(
            name='TimeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(blank=True, db_column='orderPosition', null=True)),
                ('label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'timeHour',
            },
        ),
        migrations.CreateModel(
            name='UserFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_faculties', to='webapp.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.department')),
                ('grade_year', models.ForeignKey(blank=True, db_column='gradeYear_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.gradeyear')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.classroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.teacher')),
            ],
            options={
                'db_table': 'ders_plan_generator',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='yil', null=True)),
                ('semester', models.CharField(max_length=45, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.course')),
                ('time_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.timeday')),
                ('time_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.timehour')),
            ],
            options={
                'db_table': 'timeTable',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_time', models.IntegerField(db_column='oldtime', null=True)),
                ('new_time', models.IntegerField(db_column='new_time', null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.department')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.teacher')),
            ],
            options={
                'db_table': 'editor',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='webapp.faculty'),
        ),
        migrations.CreateModel(
            name='CourseVsRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.IntegerField(blank=True, db_column='lessonType', null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='webapp.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='webapp.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_vs_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_vs_room',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='webapp.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='practice_room_type',
            field=models.ForeignKey(blank=True, db_column='uygulamaRoomType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_courses', to='webapp.roomtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='webapp.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='theory_room_type',
            field=models.ForeignKey(blank=True, db_column='teorikRoomType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_courses', to='webapp.roomtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(blank=True, db_column='courseType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='webapp.coursetype'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='webapp.department'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.ForeignKey(blank=True, db_column='roomType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='webapp.roomtype'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
