# Generated by Django 3.1.7 on 2021-04-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaculty',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_faculties', to='webapp.faculty'),
        ),
    ]
